application: pyshoppe
version: 2
runtime: python27
api_version: 1
threadsafe:  true
handlers:

- url: /content
  static_dir: content


- url: /.*
  script: pyshoppe.app

- url: /.imagedecorators
  static_dir: imagedecorators

inbound_services:
- channel_presence
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- warmup