application: pyshoppe
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

  - url: /content
    static_dir: content


  - url: /.*
    script: pyshoppe.py

libraries:
- name: webapp2
  version: "2.5.2"




